### ISSUE TITLE
Tasks and Goals - Linked (assets) Concerns and associations

### ISSUE THREAD

**Issue by D-Dev** [failys/cairis#202]
### Expected behaviour
Assuming the CAIRIS project was first built using/linking assets (systems, people data etc) - 
When creating a Task, you can associate its related/dependent assets "Concerns" first, and then where an asset 'has a' relation/dependency with another.

You can also create a matching main Goal (and sub-goals) and again associate its related/dependent assets "Concerns" first, and then where an asset 'has a' relation/dependency with another.

### Actual behaviour
This is actually a lot of work and duplication (more so with multiple views), which you then do again (or duplicate) when creating the Goal. If as a user I may then be subject to human error, what if I didn't associate the asset and its related asset in the same way in the Task and the Goal. Is there something in CAIRIS that may highlight this problem. AND, is this different or a problem to how assets were originally associated/related in the Asset modelling? This is main question.

Moreover, this still assumes I am from Bravo. But what if Charlie does something similar in their view (being used external to Bravo). If we joined these views later (perhaps as per the current 'Overview' environment), we may want some alarm bells to show conflicts not just for the independent system, but also the SoS (albeit, the view is one big system to CAIRIS, so the point is the same either way)

### Steps to reproduce the behaviour
An example of this is in TMN20180329, e.g. (Charlie)(F1) & (F2) Main Goals and its related Tasks. Although, as these were last few after many, when I realised I had the wrong relation, I corrected it and moved on (although didn't see anything odd in the models to alert me), so I would need to purposely add this in again to test for issues. I thought it may be useful feedback though.

### Version of CAIRIS
Git Pull on 28 March 2018

### Operating Systems / Hardware 
Windows 7 with VMware using Ubuntu17 and Linux Chrome

**Comment by failys** [comment]
If I read this correctly, you have created a task (_everyday work activity_) and added a task concern from an asset (_A1_), created a goal with the same name as the task (_everyday work activity_), and you want to automatically add a goal concern, linking _A1_ to this goal, because it shares the same name as the pre-existing task.

I'm not convinced this is a good idea, for a number of reasons:

1.  Goals and tasks are conceptually different things.  Goals are goals the system needs to satisfy.  Tasks describe work which is carried out, presumably when goals are satisfied.
2.  It seems you should really be thinking about what goals need to be satisfied for _everyday work activity_ to run to its conclusion as you've written it, i.e. you should be working bottom-up rather than top-down.   Tasks are carried out by people, who may choose not to carry out the task.  Making the satisfaction of system goals contingent on the successful completion of a task (rather than the other way around) could get very messy.

Does this make sense?
