### ISSUE TITLE
Question: What score for value_types vulnerability_type/threat_type?

### ISSUE THREAD

**Issue by nathanjenx** [failys/cairis#368]
When creating a new vulnerability_type and/or threat_type via the CAIRIS API, what value should be selected for score?

I assumed it'd be -1 as a score doesn't seem relevant and that's what Swagger says to do in that case. However if we were to create these values from the UI they are given a value of 0.

**Comment by failys** [comment]
You don't need to select scores for these particular 'types'.  

My advice when it comes to threat and vulnerability types is, unlikely you have overwhelming reason not to do otherwise, to re-use the threat/vulnerability type templates that come with CAIRIS.  You can find these examples/threat_vulnerability_types directory.  Personally, I find the types ics_ty_types.xml pretty versatile.

**Comment by nathanjenx** [comment]
Ok perfect thank you! I was using the owasp_tv_types.xml as a baseline however I think the ics_tv_types.xml looks possibly more immediately understandable!
